application: media-snak
version: 1-test1
runtime: python
api_version: 1

builtins:
- remote_api: on

inbound_services:
- warmup

skip_files:
- ^(.*/)?app\.ya?ml
- ^(.*/)?index\.ya?ml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?development-files/.*

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine/appstats/ui.py

- url: /((about|static).*)?
  script: djangoappengine/main/main.py
  
- url: /.+
  script: djangoappengine/main/main.py
  login: required
