application: media-snak
version: 2
runtime: python
api_version: 1

builtins:
- remote_api: on
- deferred: on

inbound_services:
- warmup

skip_files:
- ^(.*/)?app\.ya?ml
- ^(.*/)?index\.ya?ml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?development-files/.*

handlers:
# These two were put here by Django, they're probably important
- url: /_ah/queue/deferred
  script: djangoappengine/deferred/handler.py
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine/appstats/ui.py

# Handler for cronjobs (admin login required)
- url: /cron/.*
  script: djangoappengine/main/main.py
  login: admin

# Static files (stylesheet, etc)
- url: /static
  static_dir: msnak/static

# Special static file rule for robots.txt
- url: /robots.txt
  static_files: msnak/static/robots.txt
  upload: msnak/static/robots.txt  

# Handler for content not requiring user login
# (main page, static content, about pages)
- url: /((about|static).*)?
  script: djangoappengine/main/main.py
  
# Handler for everything else (login required)
- url: /.+
  script: djangoappengine/main/main.py
  login: required
